/* bridge.c — CGO shim: Go nanoMutationBridge → C mutation_provider_fn */
#include "sorokin.h"

/* Generated by CGO from //export nanoMutationBridge */
extern int nanoMutationBridge(char *word, void *results, int max_results);

int nano_bridge_shim(const char *word,
    char results[][MAX_WORD_LEN], int max_results) {
    return nanoMutationBridge((char *)word, (void *)results, max_results);
}
